//! `foundry.lock` lockfile read/write.
//!
//! The lockfile records the exact resolved package versions and their
//! BLAKE3 content hashes. It should be committed to version control.
//!
//! ## Lockfile Format
//!
//! The lockfile is TOML. Each resolved package is a `[[package]]` entry:
//!
//! ```toml
//! # foundry.lock — generated by forge, do not edit manually
//! # Forge version: 0.1.0-pre-alpha
//!
//! [[package]]
//! name = "jeshua/my-lib"
//! version = "1.2.3"
//! integrity = "blake3:a1b2c3d4..."
//! url = "https://registry.forgejs.com/packages/jeshua/my-lib/1.2.3.tar.gz"
//! ```
//!
//! ## Why BLAKE3
//!
//! BLAKE3 was chosen over SHA-256 (used by npm) because:
//! - 2-3x faster on modern CPUs
//! - Supports streaming and parallelism
//! - Designed post-SHA-2, with stronger security properties
//! - Produces a compact 32-byte hash (64 hex chars)
//!
//! The integrity string format is `blake3:<hex>` to be self-describing
//! and forward-compatible with future hash algorithm changes.

use serde::{Deserialize, Serialize};

use crate::error::FoundryError;
use crate::resolver::dependency_graph::{ResolvedGraph, ResolvedPackage};

/// The lockfile format on disk.
#[derive(Debug, Serialize, Deserialize)]
struct Lockfile {
    /// The list of resolved packages.
    #[serde(rename = "package")]
    pub packages: Vec<ResolvedPackage>,
}

/// Write a resolved graph to `foundry.lock`.
pub fn write_lockfile(graph: &ResolvedGraph, path: &camino::Utf8Path) -> Result<(), FoundryError> {
    let mut packages: Vec<ResolvedPackage> = graph.packages.values().cloned().collect();
    packages.sort_by(|a, b| a.name.cmp(&b.name));

    let lockfile = Lockfile { packages };

    let toml_content = toml::to_string_pretty(&lockfile).map_err(|e| {
        FoundryError::ManifestParse {
            path: path.to_string(),
            message: e.to_string(),
        }
    })?;

    let header = format!(
        "# foundry.lock — generated by forge, do not edit manually\n# Forge version: {}\n\n",
        env!("CARGO_PKG_VERSION")
    );

    std::fs::write(path, format!("{}{}", header, toml_content))?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;

    #[test]
    fn test_lockfile_roundtrip() {
        let temp_dir = std::env::temp_dir();
        let lockfile_path = camino::Utf8PathBuf::from_path_buf(temp_dir).unwrap().join("foundry.lock");

        let mut packages = HashMap::new();
        packages.insert(
            "jeshua/my-lib".to_string(),
            ResolvedPackage {
                name: "jeshua/my-lib".to_string(),
                version: "1.2.3".to_string(),
                integrity: "blake3:a1b2c3d4".to_string(),
                download_url: "https://registry.forgejs.com/packages/jeshua/my-lib/1.2.3.tar.gz".to_string(),
            },
        );
        packages.insert(
            "alice/another-lib".to_string(),
            ResolvedPackage {
                name: "alice/another-lib".to_string(),
                version: "0.1.0".to_string(),
                integrity: "blake3:e5f6g7h8".to_string(),
                download_url: "https://registry.forgejs.com/packages/alice/another-lib/0.1.0.tar.gz".to_string(),
            },
        );

        let graph = ResolvedGraph { packages };

        // Write to lockfile
        write_lockfile(&graph, &lockfile_path).unwrap();

        // Read from lockfile
        let read_graph = read_lockfile(&lockfile_path).unwrap();

        assert_eq!(graph, read_graph);

        // Verify header and sorting
        let content = std::fs::read_to_string(&lockfile_path).unwrap();
        assert!(content.contains("# foundry.lock — generated by forge, do not edit manually"));

        // "alice/another-lib" should come before "jeshua/my-lib" due to sorting
        assert!(content.find("alice/another-lib").unwrap() < content.find("jeshua/my-lib").unwrap());

        std::fs::remove_file(lockfile_path).unwrap();
    }
}

/// Read a `foundry.lock` file and return the resolved graph.
pub fn read_lockfile(path: &camino::Utf8Path) -> Result<ResolvedGraph, FoundryError> {
    let content = std::fs::read_to_string(path)?;
    let lockfile: Lockfile = toml::from_str(&content).map_err(|e| FoundryError::ManifestParse {
        path: path.to_string(),
        message: e.to_string(),
    })?;

    let packages = lockfile
        .packages
        .into_iter()
        .map(|p| (p.name.clone(), p))
        .collect();

    Ok(ResolvedGraph { packages })
}
