//! `foundry.lock` lockfile read/write.
//!
//! The lockfile records the exact resolved package versions and their
//! BLAKE3 content hashes. It should be committed to version control.
//!
//! ## Lockfile Format
//!
//! The lockfile is TOML. Each resolved package is a `[[package]]` entry:
//!
//! ```toml
//! # foundry.lock — generated by forge, do not edit manually
//! # Forge version: 0.1.0-pre-alpha
//!
//! [[package]]
//! name = "jeshua/my-lib"
//! version = "1.2.3"
//! integrity = "blake3:a1b2c3d4..."
//! url = "https://registry.forgejs.com/packages/jeshua/my-lib/1.2.3.tar.gz"
//! ```
//!
//! ## Why BLAKE3
//!
//! BLAKE3 was chosen over SHA-256 (used by npm) because:
//! - 2-3x faster on modern CPUs
//! - Supports streaming and parallelism
//! - Designed post-SHA-2, with stronger security properties
//! - Produces a compact 32-byte hash (64 hex chars)
//!
//! The integrity string format is `blake3:<hex>` to be self-describing
//! and forward-compatible with future hash algorithm changes.

use crate::error::FoundryError;
use crate::resolver::dependency_graph::ResolvedGraph;

/// Write a resolved graph to `foundry.lock`.
pub fn write_lockfile(graph: &ResolvedGraph, path: &camino::Utf8Path) -> Result<(), FoundryError> {
    let _ = (graph, path);
    // TODO: Serialize graph to TOML lockfile format
    Ok(())
}

/// Read a `foundry.lock` file and return the resolved graph.
pub fn read_lockfile(path: &camino::Utf8Path) -> Result<ResolvedGraph, FoundryError> {
    let _ = path;
    // TODO: Parse lockfile TOML
    Ok(ResolvedGraph::default())
}
