//! `foundry.lock` lockfile read/write.
//!
//! The lockfile records the exact resolved package versions and their
//! BLAKE3 content hashes. It should be committed to version control.
//!
//! ## Lockfile Format
//!
//! The lockfile is TOML. Each resolved package is a `[[package]]` entry:
//!
//! ```toml
//! # foundry.lock — generated by forge, do not edit manually
//! # Forge version: 0.1.0-pre-alpha
//!
//! [[package]]
//! name = "jeshua/my-lib"
//! version = "1.2.3"
//! integrity = "blake3:a1b2c3d4..."
//! url = "https://registry.forgejs.com/packages/jeshua/my-lib/1.2.3.tar.gz"
//! ```
//!
//! ## Why BLAKE3
//!
//! BLAKE3 was chosen over SHA-256 (used by npm) because:
//! - 2-3x faster on modern CPUs
//! - Supports streaming and parallelism
//! - Designed post-SHA-2, with stronger security properties
//! - Produces a compact 32-byte hash (64 hex chars)
//!
//! The integrity string format is `blake3:<hex>` to be self-describing
//! and forward-compatible with future hash algorithm changes.

use serde::{Deserialize, Serialize};

use crate::error::FoundryError;
use crate::resolver::dependency_graph::{ResolvedGraph, ResolvedPackage};

#[derive(Debug, Serialize, Deserialize)]
struct Lockfile {
    #[serde(rename = "package", default, skip_serializing_if = "Vec::is_empty")]
    packages: Vec<LockfilePackage>,
}

#[derive(Debug, Serialize, Deserialize)]
struct LockfilePackage {
    name: String,
    version: String,
    integrity: String,
    url: String,
}

/// Write a resolved graph to `foundry.lock`.
pub fn write_lockfile(graph: &ResolvedGraph, path: &camino::Utf8Path) -> Result<(), FoundryError> {
    let mut packages: Vec<LockfilePackage> = graph
        .packages
        .values()
        .map(|pkg| LockfilePackage {
            name: pkg.name.clone(),
            version: pkg.version.clone(),
            integrity: pkg.integrity.clone(),
            url: pkg.download_url.clone(),
        })
        .collect();

    // Sort by name for deterministic lockfiles
    packages.sort_by(|a, b| a.name.cmp(&b.name));

    let lockfile = Lockfile { packages };

    let toml_string = toml::to_string(&lockfile).map_err(|e| FoundryError::ManifestParse {
        path: path.to_string(),
        message: format!("failed to serialize lockfile: {}", e),
    })?;

    let mut out = String::new();
    out.push_str("# foundry.lock — generated by forge, do not edit manually\n");
    out.push_str("# Forge version: 0.1.0-pre-alpha\n\n");
    out.push_str(&toml_string);

    std::fs::write(path, out)?;

    Ok(())
}

/// Read a `foundry.lock` file and return the resolved graph.
pub fn read_lockfile(path: &camino::Utf8Path) -> Result<ResolvedGraph, FoundryError> {
    let content = std::fs::read_to_string(path)?;

    let lockfile: Lockfile = toml::from_str(&content).map_err(|e| FoundryError::ManifestParse {
        path: path.to_string(),
        message: format!("failed to parse lockfile: {}", e),
    })?;

    let mut graph = ResolvedGraph::default();

    for pkg in lockfile.packages {
        graph.packages.insert(
            pkg.name.clone(),
            ResolvedPackage {
                name: pkg.name,
                version: pkg.version,
                integrity: pkg.integrity,
                download_url: pkg.url,
            },
        );
    }

    Ok(graph)
}
