//! `forge new <name>` — Create a new Forge project.
//!
//! Scaffolds a new Forge project with:
//! - `forge.toml` with sensible defaults
//! - `app/root.fx` — root layout component
//! - `app/routes.fx` — route definitions
//! - `app/pages/Home.fx` — welcome page
//! - `schema.fx` — empty database schema
//! - `foundry.lock` — empty lockfile
//!
//! Optionally prompts for:
//! - Deployment targets (server, edge, desktop, mobile)
//! - Database adapter (SQLite default, PostgreSQL)
//! - Authentication (email+password, passkey, OAuth)

use anyhow::{Context, Result};
use clap::Args;
use std::fs;
use std::path::PathBuf;

#[derive(Debug, Args)]
pub struct NewArgs {
    /// Name of the new project
    pub name: String,
    /// Skip interactive prompts and use defaults
    #[arg(long, short)]
    pub yes: bool,
}

pub async fn run(args: NewArgs) -> Result<()> {
    crate::output::info(&format!("Creating new Forge project: {}", args.name));

    let base_path = PathBuf::from(&args.name);

    // Create directory structure
    fs::create_dir_all(base_path.join("app").join("pages"))
        .with_context(|| format!("Failed to create project directories in {}", args.name))?;

    // Write forge.toml
    let forge_toml_content = format!(
        r#"[project]
name = "{}"
version = "0.1.0"

[build]
entry = "app/root.fx"
output = ".forge/dist"
"#, args.name);
    fs::write(base_path.join("forge.toml"), forge_toml_content)?;

    // Write app/root.fx
    let root_fx_content = r#"export default function Root({ children }) {
  return (
    <html>
      <head>
        <title>New Forge App</title>
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
"#;
    fs::write(base_path.join("app").join("root.fx"), root_fx_content)?;

    // Write app/routes.fx
    let routes_fx_content = r#"import Home from './pages/Home.fx';

export default [
  { path: '/', component: Home },
];
"#;
    fs::write(base_path.join("app").join("routes.fx"), routes_fx_content)?;

    // Write app/pages/Home.fx
    let home_fx_content = r#"export default function Home() {
  return <h1>Welcome to Forge!</h1>;
}
"#;
    fs::write(base_path.join("app").join("pages").join("Home.fx"), home_fx_content)?;

    // Write schema.fx
    fs::write(base_path.join("schema.fx"), "// Empty database schema\n")?;

    // Write foundry.lock
    fs::write(base_path.join("foundry.lock"), "# foundry.lock — generated by forge, do not edit manually\n")?;

    crate::output::success(&format!(
        "Created {} — run `cd {} && forge dev` to start",
        args.name, args.name
    ));
    Ok(())
}
